#на3 #на4
Исключение - особый вид объектов, предназначенный для сообщения программисту/пользователю/другим частям программы о произошедшей ошибке.
Выбрасываются либо в результате ошибки в коде, либо с помощью `throw`. Параметр `throw` - экземпляр класса, наследующего **Throwable** (см [[Throwable-Exception-Error]])

Контролируемые исключения возникают во время компиляции кода, если их не обработать, программа не будет компилироваться. Это исключительные случаю, которые нужно обработать. Например `FileNotFoundException`.
Неконтролируемые исключения возникают во время выполнения программы. То есть программа компилируется и ошибка выводится во время выполнения. Например `RunTimeExpection`, `ArrayIndexOutOfBoundsException`.
Ловится с помощью try-catch:
```java
try {
	//Код, где может выпасть исключение
} catch (SomeKindOfException ex) {
	//Обратка исключения
} finally {
	//То, что выполнится в любом случае
}
```
Часть исключений, не отлавливаемых в рамках метода, необходимо указывать в сигнатуре с помощью ключевого слова `throws`. Так необходимо поступать с контролируемыми исключениями. К ним относятся все наследники Exception, кроме _RuntimeException и его наследников_.